name: Rainfall Prediction CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start MLflow tracking server
      run: |
        mkdir -p mlruns
        nohup mlflow server \
          --backend-store-uri ./mlruns \
          --default-artifact-root ./mlruns \
          --host 127.0.0.1 \
          --port 5000 > mlflow.log 2>&1 &
        sleep 10  # wait for MLflow server to start

    - name: Run training script
      run: python src/train.py

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/rainfall-prediction:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/rainfall-prediction:latest
